[color-theme]
name = "Cascade Dark"

[color-theme.base]
white = "#fcfcfa"
black = "#0f121a"
grey = "#131720"
blue = "#7cafc2"
red = "#E26674"
yellow = "#ffd866"
orange = "#eab780"
green = "#a9dc76"
purple = "#D59DF6"
cyan = "#506686"
magenta = "#ab9df2"

[color-theme.syntax]
attribute = "$orange"
builtinType = "$cyan"
comment = "$cyan"
constant = "#58b4ff"
constructor = "$orange"
embedded = "$cyan"
enum = "$orange"
enum-member = "$red"
enumMember = "$orange"
escape = "$cyan"
field = "$red"
function = "$blue"
"function.method" = "$orange"
interface = "#DD46C2"
keyword = "$purple"
"keyword.control" = "$purple"
macro = "#28A9FF"
method = "#28A9FF"
number = "$yellow"
operator = "#EEEEEE60"
property = "#FF7135"
selfKeyword = "#14E5D4"
string = "#B3D667"
struct = "$orange"
structure = "$orange"
symbol = "$yellow"
type = "$orange"
"type.builtin" = "$cyan"
typeAlias = "#b079ee"
variable = "$red"
"variable.other.member" = "$red"
"variable.parameter" = "$red"

[color-theme.ui]
"activity.background" = "$black"
"activity.current" = "#353535"
"completion.background" = "$grey"
"completion.current" = "#353535"
"completion_lens.foreground" = "#5C6370"
"editor.background" = "$grey"
"editor.caret" = "$cyan"
"editor.current_line" = "#181d29"
"editor.dim" = "$cyan"
"editor.drag_drop_background" = "#79c1fc55"
"editor.drag_drop_tab_background" = "$red"
"editor.focus" = "$white"
"editor.foreground" = "$white"
"editor.indent_guide" = "$grey"
"editor.link" = "$cyan"
"editor.selection" = "#e6eeff21"
"editor.sticky_header_background" = ""
"editor.visible_whitespace" = "#5C6370"
"error_lens.error.background" = "#141414"
"error_lens.error.foreground" = "#FA3232"
"error_lens.other.background" = "#5C637020"
"error_lens.other.foreground" = "#b0b0b0"
"error_lens.warning.background" = "#141414"
"error_lens.warning.foreground" = "$yellow"
"hover.background" = "$black"
"inlay_hint.background" = "$black"
"inlay_hint.foreground" = "$cyan"
"lapce.active_tab" = "#161616"
"lapce.border" = "$grey"
"lapce.button.primary.background" = "#50a14f"
"lapce.button.primary.foreground" = ""
"lapce.dropdown_shadow" = "#020202"
"lapce.error" = "#ff6188"
"lapce.icon.active" = "$white"
"lapce.icon.inactive" = "#5C6370"
"lapce.inactive_tab" = "#101014"
"lapce.plugin.author" = "#B0B0B0"
"lapce.plugin.description" = "$white"
"lapce.plugin.name" = "#DDDDDD"
"lapce.remote.connected" = "#50A14F"
"lapce.remote.connecting" = "#C18401"
"lapce.remote.disconnected" = "#E45649"
"lapce.remote.icon" = "$black"
"lapce.remote.local" = "#4078F2"
"lapce.scroll_bar" = "$magenta"
"lapce.tab.active.background" = "#1c212e"
"lapce.tab.active.foreground" = "$white"
"lapce.tab.active.underline" = "$red"
"lapce.tab.inactive.background" = "#1c212e"
"lapce.tab.inactive.foreground" = "$cyan"
"lapce.tab.inactive.underline" = "#528BFF77"
"lapce.tab.separator" = "#1c212e"
"lapce.warn" = "$red"
"markdown.blockquote" = "#a9dc76"
"palette.background" = "$black"
"palette.current" = "#262626"
"palette.current.background" = "#2C313A"
"palette.current.foreground" = "$white"
"palette.foreground" = "$white"
"panel.background" = "$black"
"panel.current" = "#262626"
"panel.current.background" = "#2C313A"
"panel.current.foreground" = "$white"
"panel.current.foreground.dim" = "#5C6370"
"panel.foreground" = "$white"
"panel.foreground.dim" = "#5C6370"
"panel.hovered" = "#595959"
"panel.hovered.background" = "#343A45"
"panel.hovered.foreground" = "$white"
"panel.hovered.foreground.dim" = "#5C6370"
"source_control.added" = "#a9dc76"
"source_control.modified" = "#78dce8"
"source_control.removed" = "#727072"
"status.background" = "$black"
"status.foreground" = "$white"
"status.modal.insert" = "$red"
"status.modal.insert.background" = "$red"
"status.modal.insert.foreground" = "$black"
"status.modal.normal" = "$blue"
"status.modal.normal.background" = "$blue"
"status.modal.normal.foreground" = "$black"
"status.modal.terminal" = "$purple"
"status.modal.terminal.background" = "$purple"
"status.modal.terminal.foreground" = "$black"
"status.modal.visual" = "$yellow"
"status.modal.visual.background" = "$yellow"
"status.modal.visual.foreground" = "$black"
"terminal.background" = "$black"
"terminal.black" = "#141414"
"terminal.blue" = "#fc9867"
"terminal.bright_black" = "#161616"
"terminal.bright_blue" = "#fc9867"
"terminal.bright_cyan" = "#78dce8"
"terminal.bright_green" = "#a9dc76"
"terminal.bright_magenta" = "#ab9df2"
"terminal.bright_red" = "#ff6188"
"terminal.bright_white" = "#fcfcfa"
"terminal.bright_yellow" = "#ffd866"
"terminal.cursor" = "#ffb638"
"terminal.cyan" = "#78dce8"
"terminal.foreground" = "#fcfcfa"
"terminal.green" = "#a9dc76"
"terminal.magenta" = "#ab9df2"
"terminal.red" = "#ff6188"
"terminal.white" = "#fcfcfa"
"terminal.yellow" = "#ffd866"

[ui]
font-family = ""
font-size = 12
icon-size = 0
header-height = 35
status-height = 25
tab-min-width = 100
scroll-width = 10
drop-shadow-width = 4
preview-editor-width = 0
hover-font-family = ""
hover-font-size = 0
trim-search-results-whitespace = true
list-line-height = 25
